version: "3.1"

services:
  frontend:
    container_name: react-client-container
#    depends_on:
#      - backend
    build:
      context: ./client/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000

#volumes:
#  mongo:

