/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.7/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "DCCV"
include(
    ":domain",
    ":application",
    ":presentation",
    ":storage",
    ":interface",
    ":interface:client",
    ":interface:server",
    ":distribution"
)

include(
    ":distribution:utilitynode",
    ":distribution:usernode",
    ":distribution:cameranode"
)

gradle.allprojects {
    version = rootProject.findProperty("version") ?: "0.1.0"
}