/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.scalatest.funsuite.AnyFunSuite
import usernode.swarmnode.App

class AppSuite extends AnyFunSuite {
}
